#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: venuedog-production
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
    TZ: "America/New_York"
  addons:
    - logentries:tryit
    - cleardb:ignite

staging:
  stack: cedar
  app: venuedog-staging
  config:
    BUNDLE_WITHOUT: "development:test"
    TZ: "America/New_York"
    RAILS_ENV: "staging"
  addons:
    - logentries:tryit
    - cleardb:ignite
